version: "3.9"

services:
  backend:
    image: "${IMAGE_TAG:-ghcr.io/OWNER/REPO:main}"
    container_name: stats-f1-backend
    restart: always
    environment:
      - APP_ENV=${APP_ENV:-production}
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis          # si tu ajoutes redis en prod
      - REDIS_PORT=6379
    ports:
      - "8000:8000"
    depends_on:
      - redis

  # Exemple frontend (si tu push aussi l'image frontend)
  frontend:
    image: "ghcr.io/OWNER/REPO-frontend:main"
    container_name: stats-f1-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redisdata:/data

volumes:
  redisdata:
